baseurl = "https://mhester.de"
title = "mhester.de"
theme = "hugo-coder-forked"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "kksudo"
enableGitInfo = true
enableRobotsTXT = true

# Hugo settings
[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[params]
author = "Matthias Hester"
info = [""]
description = "Matthias Hesters Social Networks"
keywords = "blog,businesscard,personal,devops"
#avatarURL = "ich.jpg"
gravatar = "mtthester@gmail.com"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon.png"

since = 2023
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false
# Git Commit in Footer, uncomment the line below to enable it
#commit = "https://github.com/kksudo/kazakov.xyz/tree/"
powered_by = true
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
#tag = "tags"
#author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 3
url = "https://github.com/brainscan1980/"
target = "_blank"
[[params.social]]
name = "Facebook"
icon = "fa fa-facebook fa-2x"
weight = 3
url = "https://www.facebook.com/matthias.hester/"
target = "_blank"
[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 3
url = "https://www.instagram.com/brainscan/"
target = "_blank"
[[params.social]]
name = "Twitter"
icon = "fa fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://x.com/mh2cc"
target = "_blank"
[[params.social]]
name = "Mastodon"
icon = "fa fa-brands fa-mastodon fa-2x"
weight = 3
url = "https://troet.cafe/@brainscan"
target = "_blank"
[[params.social]]
name = "Bluesky"
icon = "fa fa-brands fa-bluesky fa-2x"
weight = 3
url = "https://bsky.app/profile/mh2.in"
target = "_blank"
#[[params.social]]
#name = "Telegram"
#icon = "fa fa-telegram fa-2x"
#weight = 3
#url = "https://t.me/MatthiasHester"
#target = "_blank"
[[params.social]]
name = "m@mh2.in"
icon = "fa fa-envelope fa-2x"
weight = 6
url = "mailto:m@mh2.in"
target = "_blank"

# Menu links
[[languages.en.menu.main]]
name = "Home"
weight = 1
url  = "/"
[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"
